#install.packages('spotifyr')
library(spotifyr)
#Sys.setenv(SPOTIFY_CLIENT_ID = 'XXXXX')
#Sys.setenv(SPOTIFY_CLIENT_SECRET = 'XXXXX' )
access_token <- get_spotify_access_token()
user <- get_user_audio_features("")

top_artists <- user %>% group_by(artist_name) %>% summarise(count = n()) %>% arrange(desc(count))
g <- ggplot(head(top_artists), aes(artist_name, count))
g + geom_bar(stat='identity') + theme(axis.text.x=element_text(angle=50, hjust=1))
